import { marked } from 'marked';
import { remark } from 'remark';
import fixTypography from 'remark-typography';

const UPSTREAM_COMMIT = '7ffe6342b09eea1721892e1e274419de17f02873';
const COMPONENTS_SOURCE = `https://raw.githubusercontent.com/mui/base-ui/${UPSTREAM_COMMIT}/docs/src/app/(docs)/react/components/page.mdx`;

export const components = [
  'Accordion',
  'Alert Dialog',
  'Autocomplete',
  'Avatar',
  'Button',
  'Checkbox',
  'Checkbox Group',
  'Collapsible',
  'Combobox',
  'Context Menu',
  'Dialog',
  'Drawer',
  'Field',
  'Fieldset',
  'Form',
  'Input',
  'Menu',
  'Menubar',
  'Meter',
  'Navigation Menu',
  'Number Field',
  'OTP Field',
  'Popover',
  'Preview Card',
  'Progress',
  'Radio',
  'Scroll Area',
  'Select',
  'Separator',
  'Slider',
  'Switch',
  'Tabs',
  'Toast',
  'Toggle',
  'Toggle Group',
  'Toolbar',
  'Tooltip',
] as const;

function slug(value: string) {
  return value.toLowerCase().replaceAll(' ', '-');
}

function rewriteLinks(markdown: string) {
  return markdown
    .replaceAll('](/react/', '](https://base-ui.com/react/')
    .replace(
      /\(\.\/([a-z0-9-]+)\/page\.mdx\)/g,
      '(https://base-ui.com/react/components/$1)',
    );
}

function addHeadingIds(html: string) {
  return html.replace(/<h([1-6])>([^<]+)<\/h\1>/g, (_match, level: string, text: string) => {
    return `<h${level} id="${slug(text.replaceAll('&nbsp;', ' '))}">${text}</h${level}>`;
  });
}

async function renderMarkdown(markdown: string) {
  const chunks = markdown.split(/<details>|<\/details>/);
  const rendered: string[] = [];
  // remark-typography ships Unified v10 types while remark uses Unified v11.
  // @ts-expect-error The runtime plugin API is compatible.
  const typography = remark().use(fixTypography);

  for (let index = 0; index < chunks.length; index += 1) {
    let chunk = chunks[index];
    const insideDetails = index % 2 === 1;

    if (insideDetails) {
      chunk = chunk.replace(/^\s*<summary>Outline<\/summary>\s*/, '');
      const formatted = String(await typography.process(chunk));
      rendered.push(`<details><summary>Outline</summary>${await marked.parse(formatted)}</details>`);
    } else {
      const formatted = String(await typography.process(chunk));
      rendered.push(await marked.parse(formatted));
    }
  }

  return addHeadingIds(rendered.join(''));
}

let cached: Promise<string> | undefined;

export function getComponentsHtml(fetcher: typeof fetch) {
  cached ??= (async () => {
    const response = await fetcher(COMPONENTS_SOURCE);
    if (!response.ok) {
      throw new Error(`Unable to load the pinned Base UI components page (${response.status}).`);
    }

    const source = await response.text();
    const metadataMarker = "[//]: # 'The above section is autogenerated";
    const markdown = rewriteLinks(source.slice(0, source.indexOf(metadataMarker)));
    return renderMarkdown(markdown);
  })();

  return cached;
}

export function componentSlug(component: string) {
  return slug(component);
}
