<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'; import { composeEventHandlers } from '../shared/events.js'; import { getOTPFieldContext } from './otp-field-context.svelte.js';
  export interface Props extends Omit<HTMLInputAttributes, 'value' | 'type' | 'maxlength'> { index?: number; ref?: HTMLInputElement | null; }
  let { index: explicitIndex, ref = $bindable(null), oninput, onkeydown, onfocus, ...rest }: Props = $props(); const otp = getOTPFieldContext(); let index = $derived(explicitIndex ?? Math.max(0, otp.inputs.indexOf(ref!))); let slot = $derived(otp.value[index] ?? '');
  $effect(() => { if (ref) return otp.register(ref); });
  function input(event: Event) { const raw = (event.currentTarget as HTMLInputElement).value; const inserted = otp.normalize(raw); const chars = Array.from(otp.value.padEnd(otp.length, ' ')); chars.splice(index, inserted.length, ...inserted); const next = chars.join('').trimEnd(); otp.setValue(next, inserted.length > 1 ? 'paste' : 'input', event); queueMicrotask(() => otp.focus(Math.min(otp.length - 1, index + Math.max(1, inserted.length)))); }
  function keydown(event: KeyboardEvent) { if (event.key === 'ArrowLeft') { event.preventDefault(); otp.focus(index - 1); } if (event.key === 'ArrowRight') { event.preventDefault(); otp.focus(index + 1); } if (event.key === 'Home') { event.preventDefault(); otp.focus(0); } if (event.key === 'End') { event.preventDefault(); otp.focus(Math.min(otp.value.length, otp.length - 1)); } if (event.key === 'Backspace' && !otp.readOnly) { event.preventDefault(); const target = slot ? index : Math.max(0, index - 1); const chars = Array.from(otp.value); chars.splice(target, 1); otp.setValue(chars.join(''), 'keyboard', event); queueMicrotask(() => otp.focus(target)); } if (event.key === 'Delete' && !otp.readOnly) { event.preventDefault(); const chars = Array.from(otp.value); chars.splice(index, 1); otp.setValue(chars.join(''), 'keyboard', event); } }
</script>
<input bind:this={ref} {...rest} id={`${otp.baseId}-input-${index}`} value={slot} type={otp.mask ? 'password' : 'text'} inputmode={otp.validationType === 'numeric' ? 'numeric' : 'text'} autocomplete={index === 0 ? 'one-time-code' : 'off'} maxlength={index === 0 ? otp.length : 1} tabindex={index === Math.min(otp.value.length, otp.length - 1) ? 0 : -1} disabled={otp.disabled} readonly={otp.readOnly} required={otp.required && index === 0} aria-label={rest['aria-label'] ?? `Character ${index + 1} of ${otp.length}`} data-filled={slot ? '' : undefined} data-active={index === Math.min(otp.value.length, otp.length - 1) ? '' : undefined} oninput={composeEventHandlers(oninput, input)} onkeydown={composeEventHandlers(onkeydown, keydown)} onfocus={composeEventHandlers(onfocus, (event) => (event.currentTarget as HTMLInputElement).select())} />
