<script lang="ts">
  import type { Snippet } from 'svelte'; import type { HTMLAttributes } from 'svelte/elements'; import type { Orientation } from '../shared/types.js'; import { getScrollAreaContext } from './scroll-area-context.svelte.js';
  export interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> { children?: Snippet; orientation?: Orientation; minSize?: number; ref?: HTMLDivElement | null; }
  let { children, orientation = 'vertical', minSize = 18, ref = $bindable(null), style, onpointerdown, ...rest }: Props = $props(); const area = getScrollAreaContext();
  let size = $derived(orientation === 'vertical' ? Math.max(minSize, area.clientHeight ** 2 / Math.max(area.scrollHeight, 1)) : Math.max(minSize, area.clientWidth ** 2 / Math.max(area.scrollWidth, 1)));
  let trackSize = $derived(orientation === 'vertical' ? area.clientHeight : area.clientWidth); let maxScroll = $derived(orientation === 'vertical' ? area.scrollHeight - area.clientHeight : area.scrollWidth - area.clientWidth); let scroll = $derived(orientation === 'vertical' ? area.scrollTop : area.scrollLeft); let position = $derived(maxScroll > 0 ? (scroll / maxScroll) * Math.max(0, trackSize - size) : 0);
  let thumbStyle = $derived(`${orientation === 'vertical' ? `height:${size}px;transform:translateY(${position}px)` : `width:${size}px;transform:translateX(${position}px)`};${typeof style === 'string' ? style : ''}`);
  function start(event: PointerEvent) { onpointerdown?.(event as PointerEvent & { currentTarget: EventTarget & HTMLDivElement }); if (event.defaultPrevented || !area.viewport || !(event.currentTarget instanceof HTMLElement)) return; event.preventDefault(); event.stopPropagation(); const startPoint = orientation === 'vertical' ? event.clientY : event.clientX; const startScroll = scroll; const target = event.currentTarget; target.setPointerCapture(event.pointerId); const move = (e: PointerEvent) => { const delta = (orientation === 'vertical' ? e.clientY : e.clientX) - startPoint; const next = startScroll + delta * (maxScroll / Math.max(1, trackSize - size)); if (orientation === 'vertical') area.viewport!.scrollTop = next; else area.viewport!.scrollLeft = next; }; const end = () => { target.removeEventListener('pointermove', move); target.removeEventListener('pointerup', end); }; target.addEventListener('pointermove', move); target.addEventListener('pointerup', end); }
</script>
<div bind:this={ref} {...rest} role="presentation" data-orientation={orientation} style={thumbStyle} onpointerdown={start}>{@render children?.()}</div>
