<script lang="ts">
  import type { Snippet } from 'svelte'; import type { OnValueChange } from '../shared/types.js'; import type { PopoverOpenReason } from '../popover/popover-context.svelte.js'; import PopoverRoot from '../popover/PopoverRoot.svelte'; import { ComboboxState, type ComboboxChangeReason, type ComboboxValue, setComboboxContext } from './combobox-context.svelte.js';
  interface Props { children?: Snippet; value?: ComboboxValue; inputValue?: string; open?: boolean; items?: unknown[]; multiple?: boolean; onValueChange?: OnValueChange<ComboboxValue, ComboboxChangeReason>; onInputValueChange?: OnValueChange<string, 'input' | 'clear'>; onOpenChange?: OnValueChange<boolean, PopoverOpenReason>; itemToString?: (item: unknown) => string; isItemEqual?: (a: unknown, b: unknown) => boolean; filter?: (item: unknown, query: string) => boolean; disabled?: boolean; readOnly?: boolean; required?: boolean; name?: string; }
  let { children, value = $bindable(null), inputValue = $bindable(''), open = $bindable(false), items = [], multiple = false, onValueChange, onInputValueChange, onOpenChange, itemToString = (item) => String(item ?? ''), isItemEqual = Object.is, filter, disabled = false, readOnly = false, required = false, name }: Props = $props(); const uid = $props.id(); const box = setComboboxContext(new ComboboxState()); box.inputId = `${uid}-input`; box.listId = `${uid}-list`; box.labelId = `${uid}-label`;
  box.select = (item, reason, event) => { if (disabled || readOnly) return; if (multiple) { const current = Array.isArray(value) ? value : value == null ? [] : [value]; value = current.some((candidate) => isItemEqual(candidate, item)) ? current.filter((candidate) => !isItemEqual(candidate, item)) : [...current, item]; } else { value = item; inputValue = itemToString(item); open = false; } onValueChange?.(value, { reason, event }); };
  box.setInputValue = (next, event) => { inputValue = next; box.inputValue = next; onInputValueChange?.(next, { reason: 'input', event }); };
  box.clear = (event) => { value = multiple ? [] : null; inputValue = ''; onValueChange?.(value, { reason: 'clear', event }); onInputValueChange?.('', { reason: 'clear', event }); };
  $effect.pre(() => { box.value = value; box.inputValue = inputValue; box.sourceItems = items; box.multiple = multiple; box.disabled = disabled; box.readOnly = readOnly; box.required = required; box.name = name; box.itemToString = itemToString; box.isItemEqual = isItemEqual; box.filter = filter ?? ((item, query) => itemToString(item).toLocaleLowerCase().includes(query.toLocaleLowerCase())); });
</script>
<PopoverRoot bind:open onOpenChange={(next, details) => { open = next; onOpenChange?.(next, details); }}>{@render children?.()}</PopoverRoot>
{#if name}{#each box.selectedValues as selected}<input type="hidden" name={multiple ? `${name}[]` : name} value={itemToString(selected)} />{/each}{/if}
